version: "3.5"
services:

  admin-microservice:
    image: gcit/admin_microservice
    depends_on:
      - db
      - monitor
    deploy:
      placement:
        constraints: [node.role == worker]
    command:
      - --server.port=80
      - --spring.boot.admin.url=http://monitor:80/
      - --spring.datasource.url=jdbc:mysql://db:3306/library
      - --spring.datasource.username=microservice
      - --spring.datasource.password=microservice

  librarian-microservice:
    image: gcit/librarian_microservice
    depends_on:
      - db
      - monitor
    deploy:
      placement:
        constraints: [node.role == worker]
    command:
      - --server.port=80
      - --spring.boot.admin.url=http://monitor:80/
      - --spring.datasource.url=jdbc:mysql://db:3306/library
      - --spring.datasource.username=microservice
      - --spring.datasource.password=microservice
    
  borrower-microservice:
    image: gcit/borrower_microservice
    depends_on:
      - db
      - monitor
    deploy:
      placement:
        constraints: [node.role == worker]
    command:
      - --server.port=80
      - --spring.boot.admin.url=http://monitor:80/
      - --spring.datasource.url=jdbc:mysql://db:3306/library
      - --spring.datasource.username=microservice
      - --spring.datasource.password=microservice

  service-master:
    image: gcit/service_master
    ports:
      - 80:80
    depends_on:
      - monitor
      - admin-microservice
      - librarian-microservice
      - borrower-microservice
    deploy:
      placement:
        constraints: [node.role == worker]
    command:
      - --server.port=80
      - --spring.boot.admin.url=http://monitor:80
      - --servicemaster.adminservice.url=http://admin-microservice:80/
      - --servicemaster.librarianservice.url=http://librarian-microservice:80/
      - --servicemaster.borrowerservice.url=http://borrower-microservice:80/

  monitor:
    image: gcit/monitor
    ports: 
      - 8000:80
    deploy:
      placement:
        constraints: [node.role == worker]
    command:
      - --server.port=80

  db:
    image: mysql:5.5
    deploy:
      replicas: 1
    ports:
      - 3306:3306
    volumes:
      - type: volume
        source: mysql-data
        target: /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: library
      MYSQL_USER: microservice
      MYSQL_PASSWORD: microservice
volumes:
  mysql-data: