#!/bin/bash
MICROSERVICES="admin_microservice borrower_microservice librarian_microservice service_master monitor"

for MICROSERVICE in $MICROSERVICES; do
    mkdir -p $MICROSERVICE
    DOCKER_FILE="./$MICROSERVICE/Dockerfile"
    touch $DOCKER_FILE
    echo -e "# IMPORTANT NOTE: This file is auto-generated by ../$0.\n# Please DO NOT modify by any cost. Generate this instead :)" > $DOCKER_FILE
    echo -e "FROM openjdk:8-jre-slim\nMAINTAINER me@feeliks.com\nCOPY ./$MICROSERVICE.jar /$MICROSERVICE.jar\nENTRYPOINT [\"java\", \"-jar\", \"/$MICROSERVICE.jar\"]" \
        >> $DOCKER_FILE
done
